Document: mesaplot
Title: Debian mesaplot Manual
Author: <insert document author here>
Abstract: This manual describes what mesaplot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mesaplot/mesaplot.sgml.gz

Format: postscript
Files: /usr/share/doc/mesaplot/mesaplot.ps.gz

Format: text
Files: /usr/share/doc/mesaplot/mesaplot.text.gz

Format: HTML
Index: /usr/share/doc/mesaplot/html/index.html
Files: /usr/share/doc/mesaplot/html/*.html
