#!/bin/sh
# postinst script for mesaplot
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        chmod 666 /usr/lib/python2.7/dist-packages/mesaplot/config.txt
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
